language: python
dist: bionic
sudo: false
addons:
  apt:
    packages:
      - proj-bin
      - libproj-dev
python:
  - 3.5
  - 3.6
  - 3.7
env:
  global:
    - PIP_INDEX_URL=https://pypi.pacificclimate.org/simple

install:
  - pip install -r requirements.txt .
  - pip install -r test_requirements.txt .
  - pip install .
script:
  - flake8 climpyrical/
  - py.test -v climpyrical/tests
