name: Documentation Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run : |
        sudo apt-get install -y proj-bin libproj-dev r-base
        pip install -r requirements.txt
        pip install pdoc3==0.9.1
        pip install .
        ./r_install.sh
    - name: Genereate docs
      run: pdoc --html -o docs --force climpyrical/*.py
    - name: Check for changes
      run: echo "::set-env name=CHANGES::$( git diff )"
    - name: Changes detected, run `make docs` to generate new documentation
      run: exit 1
      if: env.CHANGES != ''
    - run: echo "No changes detected"
      if: env.CHANGES == ''
