name: Python CI

on: push

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y proj-bin libproj-dev libharfbuzz-dev libfribidi-dev libcurl4-openssl-dev  r-base
        pip install -r requirements.txt -r test_requirements.txt
        pip install .
        Rscript install_pkgs.R r_requirements.txt
      env:
        PIP_INDEX_URL: https://pypi.pacificclimate.org/simple
    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        py.test -v --cov
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        py.test -m "not slow" -v
    - name: Flake8 Check
      run: |
        flake8 climpyrical/
